
on:
  pull_request:
    types: [opened, edited]
name: hithub to jira2

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}        
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Comment on issue
      uses: atlassian/gajira-comment@v3
      with:
        issue: KS-2
        comment: $(echo "${{ github.event.head_commit.message }}" | grep -Eo 'KS-[0-9]+' | head -n1) last commit ${{ github.event.head_commit.message }} ${{ github.event_name }}  https://github.com/deprinc3/Document/pull/${{ github.event.pull_request.number }}  full event is  ${{ github.event }}   
