
on:
  pull_request:
    types: [opened, edited, closed, edited, reopened]
name: hithub to jira2

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}        
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
        
    - name: Comment on issue
      uses: atlassian/gajira-comment@v3
      env:
        GH_EVENT: ${{ toJson(github) }}
      with:
        issue: ${{ github.event.pull_request.title }} | grep -oE '\b[A-Z]+-[0-9]+\b'
        comment: GHEVENT ${{ env.GH_EVENT }} ${{ github.event_name }}  https://github.com/deprinc3/Document/pull/${{ github.event.pull_request.number }}  full event is  ${{ github.event }}   
